### ISSUE TITLE
Liquid Exception: uninitialized constant ActiveSupport::Multibyte::Chars::Unicode

### ISSUE THREAD

**Issue by davidchisnall** [inukshuk/jekyll-scholar#209]
After updating Ruby to 2.4, I'm now seeing this error.  Trace:

```
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/multibyte/chars.rb:167:in `normalize': uninitialized constant ActiveSupport::Multibyte::Chars::Unicode (NameError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/latex-decode-0.2.2/lib/latex/decode/compatibility.rb:52:in `normalize_C'
	from /usr/local/lib/ruby/gems/2.4.0/gems/latex-decode-0.2.2/lib/latex/decode.rb:51:in `decode'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/filters/latex.rb:8:in `apply'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:289:in `block (2 levels) in convert!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:288:in `each_pair'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:288:in `block in convert!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:283:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:283:in `convert!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:105:in `block (3 levels) in <class:Names>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:105:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/names.rb:105:in `block (2 levels) in <class:Names>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/entry.rb:621:in `block in convert!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/entry.rb:620:in `each_pair'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/entry.rb:620:in `convert!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bibtex-ruby-4.4.4/lib/bibtex/entry.rb:613:in `convert'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-scholar-5.10.3/lib/jekyll/scholar/utilities.rb:628:in `block in cite'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-scholar-5.10.3/lib/jekyll/scholar/utilities.rb:625:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-scholar-5.10.3/lib/jekyll/scholar/utilities.rb:625:in `cite'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-scholar-5.10.3/lib/jekyll/scholar/tags/cite.rb:20:in `render'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
	from /usr/local/lib/ruby/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:123:in `render_liquid'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:76:in `render_document'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:466:in `block in render_pages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:464:in `render_pages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:193:in `render'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by inukshuk** [comment]
You can upgrade `latex-decode` to 0.3.0 that should fix the problem.

**Comment by davidchisnall** [comment]
Odd, `gem update` didn't update latex-decode.  Thanks, that fixes it.
