### ISSUE TITLE
Bibliography tag: --cited doesn't mix with --file

### ISSUE THREAD

**Issue by alzeih** [inukshuk/jekyll-scholar#229]
The fix for #90 doesn't work with  

```
{% bibliography --cited --file a %}
{% bibliography --cited  %}
```
or
```
{% bibliography --cited  %}
{% bibliography --cited --file a %}
```

so only the first bibliography tag is rendered (so the ordering changes which is rendered)

Commenting out `cited_keys.clear` in `cited_entries` renders both bibliography tags. https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L753-L754

**Comment by alzeih** [comment]
Ah, the workaround is to use:

```
{% bibliography --cited --file a --file references %}
```
n.b: this is also the fix for the error `NoMethodError: undefined method `key' for nil:NilClass` 

```
NoMethodError: undefined method `key' for nil:NilClass
  .../lib/jekyll/scholar/utilities.rb:554:in `details_file_for'
  .../lib/jekyll/scholar/utilities.rb:581:in `details_link_for'
  .../lib/jekyll/scholar/tags/bibliography.rb:66:in `block in render_items'
  .../lib/jekyll/scholar/tags/bibliography.rb:62:in `each'
  .../lib/jekyll/scholar/tags/bibliography.rb:62:in `each_with_index'
  .../lib/jekyll/scholar/tags/bibliography.rb:62:in `each'
  .../lib/jekyll/scholar/tags/bibliography.rb:62:in `map'
  .../lib/jekyll/scholar/tags/bibliography.rb:62:in `render_items'
...
```

**Comment by lgalke** [comment]
Hey there,

any updates? I'm on `jekyll-scholar 5.14.1` 

My setting:

Inside a post:
```
{% cite frankle2018lottery %}


## References

{% bibliography --cited --file references %}
```
config.yml
```
scholar:
# [...]
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
```

_bibliography/references.bib

```
---
---

@article{frankle2018lottery,
  title={The lottery ticket hypothesis: Finding sparse, trainable neural networks},
  author={Frankle, Jonathan and Carbin, Michael},
  journal={arXiv preprint arXiv:1803.03635},
  year={2018}
}
```

* No error messages during `jekyll serve`
* `(missing reference)` at cite point
* No entry in `References` section

**Comment by inukshuk** [comment]
You also need to pass `--file` to the cite tag or it won't find the entry there.

**Comment by lgalke** [comment]
Oh, thanks, I missed that! It works now.
