### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by hcitang** [inukshuk/jekyll-scholar#309]
I had great luck with jekyll scholar for several years. I recently needed to upgrade several components (ruby, jekyll and a few others), and my machine is now in a state where I cannot get even a simple jekyll site with jekyll-scholar to compile properly. I suspect it is a configuration issue, but do not know where the breakage is happening. Can anyone offer assistance on how I can fix my machine's configuration to get things to work again?

Here are my steps to repro the issue on a vanilla/small jekyll site on my machine:
```
$ jekyll new .
$ echo "gem 'jekyll-scholar', group: :jekyll_plugins" >>Gemfile
$ mkdir _bibliography _layouts
$ echo "@book{ruby, title = {The Ruby Programming Language}, author = {Flanagan, David and Matsumoto, Yukihiro}, year = {2008}, publisher = {O'Reilly Media} }">_bibliography/references.bib
$ echo "---
                                 ---
                                 <html>
                                 <head></head>
                                 <body>
                                   <h1>{{ page.entry.title }}</h1>
                                   <h2>{{ page.entry.author }}</h2>
                                   <p>{{ page.entry.abstract }}</p>
                                 </body>
                                 </html>" >_layouts/bibtex.html
$ jekyll b
Configuration file: /Users/tonyt/Repos/foo/_config.yml
            Source: /Users/tonyt/Repos/foo
       Destination: /Users/tonyt/Repos/foo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
	25: from /usr/local/bin/jekyll:23:in `<main>'
	24: from /usr/local/bin/jekyll:23:in `load'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
	22: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:79:in `process'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:189:in `generate'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:189:in `each'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:191:in `block in generate'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-scholar-6.7.0/lib/jekyll/scholar/generators/details.rb:48:in `generate'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-scholar-6.7.0/lib/jekyll/scholar/generators/details.rb:48:in `each'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-scholar-6.7.0/lib/jekyll/scholar/generators/details.rb:50:in `block in generate'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/page.rb:138:in `render'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/convertible.rb:207:in `do_layout'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/convertible.rb:207:in `tap'
/usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.1.1/lib/jekyll/convertible.rb:208:in `block in do_layout': undefined method `layouts=' for #<CiteProc::Ruby::Renderer:0x00007f8418696100> (NoMethodError)
```

For reference:
```
$ ruby -v; gem list jekyll jekyll-scholar citeproc citeproc-ruby
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

*** LOCAL GEMS ***

jekyll (4.1.1, 4.1.0)
jekyll-feed (0.14.0)
jekyll-gist (1.5.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (2.1.0)
jekyll-scholar (6.7.0)
jekyll-seo-tag (2.6.1)
jekyll-watch (2.2.1)

*** LOCAL GEMS ***

jekyll-scholar (6.7.0)

*** LOCAL GEMS ***

citeproc (1.0.10)
citeproc-ruby (1.1.12)

*** LOCAL GEMS ***

citeproc-ruby (1.1.12)
```

**Comment by hcitang** [comment]
I see this is a dupe of issue 305.

https://github.com/inukshuk/jekyll-scholar/issues/305
