### ISSUE TITLE
How to render DOI and URL as actual URLs?

### ISSUE THREAD

**Issue by Sciss** [inukshuk/jekyll-scholar#330]
Hi there,

I am using your plug-in with `chicago-author-date` style, to create a list of publications: https://www.sciss.de/texts/writings.html

Currently, the URL and DOI entries of the bibtex data are rendered as "text http", not clickable. How can I configure this to have actual links?

**Comment by Sciss** [comment]
I think I found an answer. One would first have to copy and edit the `.cls` file to _not_ render the URL in the `{{ reference }}`, and then use a custom config `bibliography_template: bib` with contents of file `_layouts/bib.html` being: 

```html
---
---
{{reference}}

<div>
    {% if entry.doi %}
    <span><a href="{{ entry.doi | prepend: 'http://doi.org/' }}">doi: {{ entry.doi }}</a></span>
    {% endif %}
    {% if entry.url %}
    <span><a href="{{ entry.url }}">{{ entry.url }}</a></span>
    {% endif %}
</div>
```

**Comment by marekyggdrasil** [comment]
@Sciss could you give some hints about how to prevent `{{ reference }}` from displaying DOI and url? I know you said to copy and edit the `.csl` file but this repository does not have any `.cls` files.

**Comment by marekyggdrasil** [comment]
I found the right style, the default is American Psychological Society (APA), I removed the `access` macro

https://github.com/inukshuk/citeproc-ruby/blob/d03c8a46b5efd36e8a42b4e85de0cf4d24ca1e7f/spec/fixtures/styles/apa.csl#L107-L161

however without this macro instead of not displaying DOI / URL it throws

```
ArgumentError: no CSL node: nil
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer.rb:38:in `render'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer/text.rb:49:in `render_text'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer.rb:46:in `render'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer/layout.rb:13:in `block in render_layout'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/csl-1.6.0/lib/csl/treelike.rb:22:in `each'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/csl-1.6.0/lib/csl/treelike.rb:22:in `each_child'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer/layout.rb:12:in `each'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer/layout.rb:12:in `map'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer/layout.rb:12:in `render_layout'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer.rb:46:in `render'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer.rb:92:in `render_bibliography'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/citeproc-ruby-1.1.14/lib/citeproc/ruby/renderer.rb:46:in `render'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/utilities.rb:695:in `render_bibliography'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/utilities.rb:484:in `reference_tag'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/utilities.rb:542:in `reference_data'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/utilities.rb:526:in `bibliography_tag'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/tags/bibliography.rb:62:in `block in render_items'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/tags/bibliography.rb:61:in `each'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/tags/bibliography.rb:61:in `each_with_index'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/tags/bibliography.rb:61:in `each'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/tags/bibliography.rb:61:in `map'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/tags/bibliography.rb:61:in `render_items'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-scholar-7.1.0/lib/jekyll/scholar/tags/bibliography.rb:27:in `render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/inclusion.rb:16:in `render'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/tags/include.rb:208:in `block in render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/tags/include.rb:206:in `render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  /Users/marek/.gem/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:131:in `render_liquid'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:194:in `render_layout'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:163:in `place_in_layouts'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:93:in `render_document'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:63:in `run'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:547:in `render_regenerated'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:531:in `each'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:531:in `block in render_docs'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:530:in `each_value'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:530:in `render_docs'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:210:in `render'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:80:in `process'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  /Users/marek/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
  /Users/marek/.rbenv/versions/2.6.3/bin/jekyll:23:in `load'
  /Users/marek/.rbenv/versions/2.6.3/bin/jekyll:23:in `<top (required)>'
```

**Comment by marekyggdrasil** [comment]
Ok got it! Solution was to keep the macro but remove the conditionals!

```
<macro name="access"/>
```
