### ISSUE TITLE
utilities.rb:144:in `map': undefined method `v' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by heidi-ann** [inukshuk/jekyll-scholar#76]
anyone know the cause of the following?
[I'm new to jekyll so i suspect its my setup]

```
$ jekyll build --trace
Configuration file: /Users/heidi/Dropbox/camtemplate/_config.yml
            Source: /Users/heidi/Dropbox/camtemplate
       Destination: public_html
      Generating...
  Liquid Exception: undefined method `v' for nil:NilClass in _layouts/userpage.html
/Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.2.2/lib/jekyll/scholar/utilities.rb:144:in `map': undefined method `v' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.2.2/lib/jekyll/scholar/utilities.rb:144:in `block in sort'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.2.2/lib/jekyll/scholar/utilities.rb:144:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.2.2/lib/jekyll/scholar/utilities.rb:144:in `sort_by'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.2.2/lib/jekyll/scholar/utilities.rb:144:in `sort'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.2.2/lib/jekyll/scholar/utilities.rb:134:in `entries'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.2.2/lib/jekyll/scholar/tags/bibliography.rb:18:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:205:in `render_all_layouts'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:239:in `do_layout'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

ruby  version 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13] on OSX

**Comment by inukshuk** [comment]
Sorry, my bad -- this is a bug that was introduced in 4.2.2 but should be fixed in 4.2.3. Thanks for reporting!
